print('======Desafio 02======')
print('Qual é a data do seu nascimento? ')
day = input('DIA = ')
month = input('MÊS = ')
year = input('ANO = ')
print('Você nasceu no dia',day,'de',month,'de',year, '!')
